name: Approval

on:
  push:
    branches:
      - '*'
  pull_request_target:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || ((github.event_name == 'pull_request_target') && (github.event.pull_request.head.repo.full_name != github.repository))
    environment: development